inherit: true

tools:
    external_code_coverage: false

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: [src/*, tests/*,code/*,searchpage/*,javascript/*,css/*]
    excluded_paths:
      - "tests/mock/"
